### ISSUE TITLE
What is the use of the DC-DC converter and what is the expected input-output voltage values?

### ISSUE THREAD

**Issue by jsanpe** [zeus074/dramtester#3]
I came across this tester while looking for a way to test my 4164 ram chips. Looks really neat. However the documentation does not specify how the dc-dc converter is used, and especifically the input-output voltages it expects.

Thanks in advance for your help

**Comment by zeus074** [comment]
Hi, the dc-dc just accept 5v input and the output must be adjusted to 12v.
One like this:  https://www.amazon.it/dp/B079H3YD8V/ref=cm_sw_em_r_mt_dp_5123NFZSSCG85CHP4JRM?_encoding=UTF8&psc=1
They are called MT3608

**Comment by jsanpe** [comment]
Thanks, maybe worth updating the readme.md to specify the 12v expected output.
Cheers
