### ISSUE TITLE
Roughly -4V instead of -5V

### ISSUE THREAD

**Issue by seanch80** [zeus074/dramtester#5]
Hello.  Taking the 5V (more realistically 4.7V if powered via USB) from the Arduino +5V pin and routing it through the diode only gives about ~4V into the 7660S, giving a resulting negative voltage of about -4V. According to the datasheet of a randomly chosen 4116 DRAM chip, the min/max acceptable values for the -5V line is -4.5V to -5.5V.

How does that work? Are typical 4116 DRAM chips not so picky when it comes to the -5V line?

Also, I wonder why the 1N4148 diode was chosen, and not a schottky diode or other with less voltage drop?

**Comment by zeus074** [comment]
Yes, you are right, the voltage could be a bit at the limit. I have seen from the tests that it works ,but to improve it without modifying the scheme, just replace the 1n4148 diode with a Schottky one such as BAT43 or similar. 
It is also possible to remove the diode and put a jumper, this was left over from the old version where I supplied the 12V externally.

**Comment by seanch80** [comment]
Thanks for the explanation. I think I will use a jumper instead of the diode then.

**Comment by seanch80** [comment]
![20220508_012113](https://user-images.githubusercontent.com/78215164/167277043-9fdeaba1-d5d4-4869-a648-1b2a07de8844.jpg)

..with the diode replaced by a jumper. 😄

**Comment by seanch80** [comment]
[DRAMTesterBase_01.zip](https://github.com/zeus074/dramtester/files/8646154/DRAMTesterBase_01.zip)

STL file of 3D printed base.

![DRAMTesterBase_01](https://user-images.githubusercontent.com/78215164/167277265-e9ac44db-9d62-4dd5-8368-a53066d1f384.jpg)

**Comment by zeus074** [comment]
good job!
I post the file on Github with thanks. 
I also added the stl for print the handle to glue all the jumpers and move them more easily between the high and low position.
👍

**Comment by seanch80** [comment]
Very nice. Thanks for sharing this project on github. It was fun to build and works great!
